### ISSUE TITLE
Getting "undefined method `twitter_handle=' for nil:NilClass on auth

### ISSUE THREAD

**Issue by ghost** [MSch/devise-twitter#1]
I've just installed the devise-twitter gem on the following system:

Ubuntu 10.04
ruby 1.8.7 (2010-01-10 patchlevel 249)
Rails 3.0.0
Warden 0.10.7
oauth 0.4.3
devise (master, 9/13/2010)
Nginx fronting Passenger

I'm adding Twitter to a sample app that I put together that does Facebook authentication using Devise's OAuth2 features.

When I attempt to authenticate using Twitter, I am correctly prompted for my Twitter credentials.  But after I submit correct credentials, the postback fails with an error.  Specifically:

undefined method `twitter_handle=' for nil:NilClass

The top of the stack trace is:

activesupport (3.0.0) lib/active_support/whiny_nil.rb:48:in `method_missing'
devise-twitter (0.1.1) lib/devise/twitter/warden.rb:12:in`_find_user_by_access_token'

and examination of the code indicates that @env['warden'].user is nil, which is causing this issue.

I've attached env['warden'] to the end of this comment.  Any idea what's going on here?  Happy to provide more info as necessary.

env['warden']: http://pastie.org/1157066

**Comment by MSch** [comment]
Hi,

it appears you are trying to connect an existing account with Twitter when you have no logged in user. Am I guessing right?

**Comment by ghost** [comment]
Actually, yes.  That wasn't my intention, but it looks like I grabbed the wrong URL.  So the bug isn't quite what I stated.  Sorry about the confusion.

**Comment by MSch** [comment]
Never mind. Does it work with the signup URL?

I should handle that case gracefully and redirect back with a flash message.

**Comment by ghost** [comment]
Yep, the sign up URL works as expected.
