### ISSUE TITLE
error with warden 1.0

### ISSUE THREAD

**Issue by dcu** [MSch/devise-twitter#7]
I am getting this error when starting my app

```
/usr/local/rvm/gems/ruby-1.9.2-p0/gems/warden-1.0.0/lib/warden/strategies.rb:11:in `add': authenticate! is not declared in the :twitter_oauth strategy (NoMethodError)
```

**Comment by dcu** [comment]
my bad

**Comment by MSch** [comment]
What was the problem? Maybe we should type it up in a FAQ?

**Comment by sferik** [comment]
I'm having this same problem. What was the issue?

**Comment by dcu** [comment]
iirc it was a bad config on the devise initializer, I just commented the following line out:

```
manager.default_strategies.unshift :twitter_oauth
```

**Comment by sferik** [comment]
I already have that line commented out. Any other suggestions?

**Comment by sferik** [comment]
I'm working in the rails3 branch of https://github.com/jnunemaker/twitter-app if you want to try to reproduce the bug. Can you please re-open this issue or should I create a new one?

**Comment by sferik** [comment]
Nevermind. I decided to use the oauth gem instead.

**Comment by dcu** [comment]
why don't you use omniauth? it's easier

**Comment by sferik** [comment]
omniauth just uses the oauth gem under the hood.
